FROM node:23-alpine

RUN apk add --no-cache \
  git \
  docker-cli \
  curl \
  jq \
  openjdk17 \
  bash \
  unzip

ENV SONAR_SCANNER_VERSION=4.7.0.2747
RUN curl -sL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip -o sonar-scanner.zip && \
    unzip sonar-scanner.zip && \
    mv sonar-scanner-${SONAR_SCANNER_VERSION} /opt/sonar-scanner && \
    ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner && \
    rm sonar-scanner.zip

ENV SONAR_SCANNER_OPTS="-Xmx512m"
ENV PATH="/opt/sonar-scanner/bin:$PATH"

RUN corepack enable && corepack prepare yarn@stable --activate

WORKDIR /workspace

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts --prefer-offline

WORKDIR /workspace/app

