FROM node:23-alpine

RUN apk add --no-cache git docker-cli curl jq bash

RUN corepack enable && corepack prepare yarn@stable --activate

RUN npm install -g sonar-scanner

WORKDIR /workspace

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --ignore-scripts --prefer-offline

WORKDIR /workspace/app

